## QQ邮箱配置，这个model解决了 yaml解析失败的 问题，是那个警告并没有错误.IDEA 的Bug.
spring:
 mail:
  host: smtp.qq.com #发送邮件服务器
  username: bmft.rola@qq.com #发送邮件的邮箱地址
  password: cczdqxxxizeadi #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的 bmft.rola@qq.com
  properties.mail.smtp.port: 465 #端口号465或587
  from: bmft.rola@qq.com # 发送邮件的地址，和上面username一致
  # 可以任意
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true
  properties.mail.smtp.ssl.enable: true
  default-encoding: utf-8